#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Character_Fluppism

#include "Basic.hpp"

#include "ABP_Character_Fluppism_classes.hpp"
#include "ABP_Character_Fluppism_parameters.hpp"


namespace SDK
{

// Function ABP_Character_Fluppism.ABP_Character_Fluppism_C.ExecuteUbergraph_ABP_Character_Fluppism
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Character_Fluppism_C::ExecuteUbergraph_ABP_Character_Fluppism(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Character_Fluppism_C", "ExecuteUbergraph_ABP_Character_Fluppism");

	Params::ABP_Character_Fluppism_C_ExecuteUbergraph_ABP_Character_Fluppism Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Character_Fluppism.ABP_Character_Fluppism_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Character_Fluppism_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Character_Fluppism_C", "BlueprintUpdateAnimation");

	Params::ABP_Character_Fluppism_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Character_Fluppism.ABP_Character_Fluppism_C.BlueprintBeginPlay
// (Event, Public, BlueprintEvent)

void UABP_Character_Fluppism_C::BlueprintBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Character_Fluppism_C", "BlueprintBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Character_Fluppism.ABP_Character_Fluppism_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Character_Fluppism_AnimGraphNode_ModifyBone_99DB893F4C24E6212264FFBE3500F59B
// (BlueprintEvent)

void UABP_Character_Fluppism_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Character_Fluppism_AnimGraphNode_ModifyBone_99DB893F4C24E6212264FFBE3500F59B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Character_Fluppism_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Character_Fluppism_AnimGraphNode_ModifyBone_99DB893F4C24E6212264FFBE3500F59B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Character_Fluppism.ABP_Character_Fluppism_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Character_Fluppism_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Character_Fluppism_C", "AnimGraph");

	Params::ABP_Character_Fluppism_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

