#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BOF_Guns

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BOF_Guns.BOF_Guns_C
// 0x0000 (0x00B0 - 0x00B0)
class UBOF_Guns_C final : public UBrickEditorObjectFilter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BOF_Guns_C">();
	}
	static class UBOF_Guns_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBOF_Guns_C>();
	}
};
static_assert(alignof(UBOF_Guns_C) == 0x000008, "Wrong alignment on UBOF_Guns_C");
static_assert(sizeof(UBOF_Guns_C) == 0x0000B0, "Wrong size on UBOF_Guns_C");

}

