#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Antenna_1x1x8

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Antenna_1x1x8.BP_Antenna_1x1x8_C
// 0x0000 (0x0168 - 0x0168)
class UBP_Antenna_1x1x8_C final : public UAntennaBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Antenna_1x1x8_C">();
	}
	static class UBP_Antenna_1x1x8_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Antenna_1x1x8_C>();
	}
};
static_assert(alignof(UBP_Antenna_1x1x8_C) == 0x000008, "Wrong alignment on UBP_Antenna_1x1x8_C");
static_assert(sizeof(UBP_Antenna_1x1x8_C) == 0x000168, "Wrong size on UBP_Antenna_1x1x8_C");

}

