#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrickDataSingleton

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BrickDataSingleton.BP_BrickDataSingleton_C
// 0x0000 (0x1570 - 0x1570)
class UBP_BrickDataSingleton_C final : public UBrickDataSingleton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BrickDataSingleton_C">();
	}
	static class UBP_BrickDataSingleton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BrickDataSingleton_C>();
	}
};
static_assert(alignof(UBP_BrickDataSingleton_C) == 0x000010, "Wrong alignment on UBP_BrickDataSingleton_C");
static_assert(sizeof(UBP_BrickDataSingleton_C) == 0x001570, "Wrong size on UBP_BrickDataSingleton_C");

}

