#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bricksville_Sign

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Bricksville_Sign.BP_Bricksville_Sign_C
// 0x0000 (0x0230 - 0x0230)
class ABP_Bricksville_Sign_C final : public AStaticMeshActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Bricksville_Sign_C">();
	}
	static class ABP_Bricksville_Sign_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bricksville_Sign_C>();
	}
};
static_assert(alignof(ABP_Bricksville_Sign_C) == 0x000008, "Wrong alignment on ABP_Bricksville_Sign_C");
static_assert(sizeof(ABP_Bricksville_Sign_C) == 0x000230, "Wrong size on ABP_Bricksville_Sign_C");

}

