#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DamageType_Explosion

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DamageType_Explosion.BP_DamageType_Explosion_C
// 0x0000 (0x0048 - 0x0048)
class UBP_DamageType_Explosion_C : public UDamageType_Explosion
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DamageType_Explosion_C">();
	}
	static class UBP_DamageType_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DamageType_Explosion_C>();
	}
};
static_assert(alignof(UBP_DamageType_Explosion_C) == 0x000008, "Wrong alignment on UBP_DamageType_Explosion_C");
static_assert(sizeof(UBP_DamageType_Explosion_C) == 0x000048, "Wrong size on UBP_DamageType_Explosion_C");

}

