#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dumpster

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Dumpster.BP_Dumpster_C
// 0x0008 (0x0238 - 0x0230)
class ABP_Dumpster_C final : public AStaticMeshActor
{
public:
	struct FRandomStream                          RandomStream;                                      // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Dumpster_C">();
	}
	static class ABP_Dumpster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Dumpster_C>();
	}
};
static_assert(alignof(ABP_Dumpster_C) == 0x000008, "Wrong alignment on ABP_Dumpster_C");
static_assert(sizeof(ABP_Dumpster_C) == 0x000238, "Wrong size on ABP_Dumpster_C");
static_assert(offsetof(ABP_Dumpster_C, RandomStream) == 0x000230, "Member 'ABP_Dumpster_C::RandomStream' has a wrong offset!");

}

