#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DetonatorCylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DetonatorCylinder.BP_DetonatorCylinder_C
// 0x0000 (0x01B8 - 0x01B8)
class UBP_DetonatorCylinder_C final : public UDetonatorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DetonatorCylinder_C">();
	}
	static class UBP_DetonatorCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DetonatorCylinder_C>();
	}
};
static_assert(alignof(UBP_DetonatorCylinder_C) == 0x000008, "Wrong alignment on UBP_DetonatorCylinder_C");
static_assert(sizeof(UBP_DetonatorCylinder_C) == 0x0001B8, "Wrong size on UBP_DetonatorCylinder_C");

}

