#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EMotor_2x2x2

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EMotor_2x2x2.BP_EMotor_2x2x2_C
// 0x0000 (0x01E8 - 0x01E8)
class UBP_EMotor_2x2x2_C final : public UMotorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EMotor_2x2x2_C">();
	}
	static class UBP_EMotor_2x2x2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EMotor_2x2x2_C>();
	}
};
static_assert(alignof(UBP_EMotor_2x2x2_C) == 0x000008, "Wrong alignment on UBP_EMotor_2x2x2_C");
static_assert(sizeof(UBP_EMotor_2x2x2_C) == 0x0001E8, "Wrong size on UBP_EMotor_2x2x2_C");

}

