#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExhaustCylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExhaustCylinder.BP_ExhaustCylinder_C
// 0x0000 (0x01A8 - 0x01A8)
class UBP_ExhaustCylinder_C final : public UExhaustBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ExhaustCylinder_C">();
	}
	static class UBP_ExhaustCylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExhaustCylinder_C>();
	}
};
static_assert(alignof(UBP_ExhaustCylinder_C) == 0x000008, "Wrong alignment on UBP_ExhaustCylinder_C");
static_assert(sizeof(UBP_ExhaustCylinder_C) == 0x0001A8, "Wrong size on UBP_ExhaustCylinder_C");

}

