#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FuelTank

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FuelTank.BP_FuelTank_C
// 0x0000 (0x0280 - 0x0280)
class ABP_FuelTank_C final : public AFuelTank
{
public:
	bool ShouldSpawnLeakOnHit(const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FuelTank_C">();
	}
	static class ABP_FuelTank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FuelTank_C>();
	}
};
static_assert(alignof(ABP_FuelTank_C) == 0x000008, "Wrong alignment on ABP_FuelTank_C");
static_assert(sizeof(ABP_FuelTank_C) == 0x000280, "Wrong size on ABP_FuelTank_C");

}

