#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FireExtinguisher

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FireExtinguisher.BP_FireExtinguisher_C
// 0x0000 (0x0278 - 0x0278)
class ABP_FireExtinguisher_C final : public AFireExtinguisher
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FireExtinguisher_C">();
	}
	static class ABP_FireExtinguisher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FireExtinguisher_C>();
	}
};
static_assert(alignof(ABP_FireExtinguisher_C) == 0x000008, "Wrong alignment on ABP_FireExtinguisher_C");
static_assert(sizeof(ABP_FireExtinguisher_C) == 0x000278, "Wrong size on ABP_FireExtinguisher_C");

}

