#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Handle_4x1x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Handle_4x1x1.BP_Handle_4x1x1_C
// 0x0000 (0x0168 - 0x0168)
class UBP_Handle_4x1x1_C final : public UHandleBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Handle_4x1x1_C">();
	}
	static class UBP_Handle_4x1x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Handle_4x1x1_C>();
	}
};
static_assert(alignof(UBP_Handle_4x1x1_C) == 0x000008, "Wrong alignment on UBP_Handle_4x1x1_C");
static_assert(sizeof(UBP_Handle_4x1x1_C) == 0x000168, "Wrong size on UBP_Handle_4x1x1_C");

}

