#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IdlerWheel

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IdlerWheel.BP_IdlerWheel_C
// 0x0000 (0x0188 - 0x0188)
class UBP_IdlerWheel_C final : public UIdlerWheelBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IdlerWheel_C">();
	}
	static class UBP_IdlerWheel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_IdlerWheel_C>();
	}
};
static_assert(alignof(UBP_IdlerWheel_C) == 0x000008, "Wrong alignment on UBP_IdlerWheel_C");
static_assert(sizeof(UBP_IdlerWheel_C) == 0x000188, "Wrong size on UBP_IdlerWheel_C");

}

