#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IncendiaryGrenade

#include "Basic.hpp"

#include "BP_Grenade_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IncendiaryGrenade.BP_IncendiaryGrenade_C
// 0x0000 (0x0280 - 0x0280)
class ABP_IncendiaryGrenade_C final : public ABP_Grenade_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IncendiaryGrenade_C">();
	}
	static class ABP_IncendiaryGrenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_IncendiaryGrenade_C>();
	}
};
static_assert(alignof(ABP_IncendiaryGrenade_C) == 0x000008, "Wrong alignment on ABP_IncendiaryGrenade_C");
static_assert(sizeof(ABP_IncendiaryGrenade_C) == 0x000280, "Wrong size on ABP_IncendiaryGrenade_C");

}

