#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Launcher_Projectile

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Launcher_Projectile.BP_Launcher_Projectile_C
// 0x0000 (0x03F0 - 0x03F0)
class ABP_Launcher_Projectile_C final : public ABrickProjectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Launcher_Projectile_C">();
	}
	static class ABP_Launcher_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Launcher_Projectile_C>();
	}
};
static_assert(alignof(ABP_Launcher_Projectile_C) == 0x000010, "Wrong alignment on ABP_Launcher_Projectile_C");
static_assert(sizeof(ABP_Launcher_Projectile_C) == 0x0003F0, "Wrong size on ABP_Launcher_Projectile_C");

}

