#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Launcher_6x1x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Launcher_6x1x1.BP_Launcher_6x1x1_C
// 0x0000 (0x02A0 - 0x02A0)
class UBP_Launcher_6x1x1_C final : public ULauncherBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Launcher_6x1x1_C">();
	}
	static class UBP_Launcher_6x1x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Launcher_6x1x1_C>();
	}
};
static_assert(alignof(UBP_Launcher_6x1x1_C) == 0x000010, "Wrong alignment on UBP_Launcher_6x1x1_C");
static_assert(sizeof(UBP_Launcher_6x1x1_C) == 0x0002A0, "Wrong size on UBP_Launcher_6x1x1_C");

}

