#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Missile_Large

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Missile_Large.BP_Missile_Large_C
// 0x0000 (0x03F0 - 0x03F0)
class ABP_Missile_Large_C : public ABrickProjectile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Missile_Large_C">();
	}
	static class ABP_Missile_Large_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Missile_Large_C>();
	}
};
static_assert(alignof(ABP_Missile_Large_C) == 0x000010, "Wrong alignment on ABP_Missile_Large_C");
static_assert(sizeof(ABP_Missile_Large_C) == 0x0003F0, "Wrong size on ABP_Missile_Large_C");

}

