#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pants_Snow

#include "Basic.hpp"

#include "BP_Pants_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Pants_Snow.BP_Pants_Snow_C
// 0x0000 (0x02A8 - 0x02A8)
class ABP_Pants_Snow_C final : public ABP_Pants_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Pants_Snow_C">();
	}
	static class ABP_Pants_Snow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pants_Snow_C>();
	}
};
static_assert(alignof(ABP_Pants_Snow_C) == 0x000008, "Wrong alignment on ABP_Pants_Snow_C");
static_assert(sizeof(ABP_Pants_Snow_C) == 0x0002A8, "Wrong size on ABP_Pants_Snow_C");

}

