#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PizzaPalace

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PizzaPalace.BP_PizzaPalace_C
// 0x0000 (0x02C0 - 0x02C0)
class ABP_PizzaPalace_C final : public ABrickBuilding
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PizzaPalace_C">();
	}
	static class ABP_PizzaPalace_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PizzaPalace_C>();
	}
};
static_assert(alignof(ABP_PizzaPalace_C) == 0x000010, "Wrong alignment on ABP_PizzaPalace_C");
static_assert(sizeof(ABP_PizzaPalace_C) == 0x0002C0, "Wrong size on ABP_PizzaPalace_C");

}

