#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Paint_Fire

#include "Basic.hpp"

#include "BP_Paint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Paint_Fire.BP_Paint_Fire_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_Paint_Fire_C final : public ABP_Paint_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Paint_Fire_C">();
	}
	static class ABP_Paint_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Paint_Fire_C>();
	}
};
static_assert(alignof(ABP_Paint_Fire_C) == 0x000008, "Wrong alignment on ABP_Paint_Fire_C");
static_assert(sizeof(ABP_Paint_Fire_C) == 0x0002B0, "Wrong size on ABP_Paint_Fire_C");

}

