#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlaneTail_10x10x16

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlaneTail_10x10x16.BP_PlaneTail_10x10x16_C
// 0x0000 (0x0168 - 0x0168)
class UBP_PlaneTail_10x10x16_C final : public UTailBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlaneTail_10x10x16_C">();
	}
	static class UBP_PlaneTail_10x10x16_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlaneTail_10x10x16_C>();
	}
};
static_assert(alignof(UBP_PlaneTail_10x10x16_C) == 0x000008, "Wrong alignment on UBP_PlaneTail_10x10x16_C");
static_assert(sizeof(UBP_PlaneTail_10x10x16_C) == 0x000168, "Wrong size on UBP_PlaneTail_10x10x16_C");

}

