#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceTimer

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RaceTimer.BP_RaceTimer_C
// 0x0000 (0x0230 - 0x0230)
class ABP_RaceTimer_C final : public ARaceTimer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RaceTimer_C">();
	}
	static class ABP_RaceTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RaceTimer_C>();
	}
};
static_assert(alignof(ABP_RaceTimer_C) == 0x000008, "Wrong alignment on ABP_RaceTimer_C");
static_assert(sizeof(ABP_RaceTimer_C) == 0x000230, "Wrong size on ABP_RaceTimer_C");

}

