#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableCornerRounded

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ScalableCornerRounded.BP_ScalableCornerRounded_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_ScalableCornerRounded_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ScalableCornerRounded_C">();
	}
	static class UBP_ScalableCornerRounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableCornerRounded_C>();
	}
};
static_assert(alignof(UBP_ScalableCornerRounded_C) == 0x000008, "Wrong alignment on UBP_ScalableCornerRounded_C");
static_assert(sizeof(UBP_ScalableCornerRounded_C) == 0x0001A0, "Wrong size on UBP_ScalableCornerRounded_C");

}

