#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableHemisphere

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ScalableHemisphere.BP_ScalableHemisphere_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_ScalableHemisphere_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ScalableHemisphere_C">();
	}
	static class UBP_ScalableHemisphere_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableHemisphere_C>();
	}
};
static_assert(alignof(UBP_ScalableHemisphere_C) == 0x000008, "Wrong alignment on UBP_ScalableHemisphere_C");
static_assert(sizeof(UBP_ScalableHemisphere_C) == 0x0001A0, "Wrong size on UBP_ScalableHemisphere_C");

}

