#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScalableZylinder

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ScalableZylinder.BP_ScalableZylinder_C
// 0x0000 (0x01A0 - 0x01A0)
class UBP_ScalableZylinder_C final : public UScalableBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ScalableZylinder_C">();
	}
	static class UBP_ScalableZylinder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScalableZylinder_C>();
	}
};
static_assert(alignof(UBP_ScalableZylinder_C) == 0x000008, "Wrong alignment on UBP_ScalableZylinder_C");
static_assert(sizeof(UBP_ScalableZylinder_C) == 0x0001A0, "Wrong size on UBP_ScalableZylinder_C");

}

