#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShadowBorder

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ShadowBorder.BP_ShadowBorder_C
// 0x0000 (0x0270 - 0x0270)
class UBP_ShadowBorder_C final : public UBorder
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ShadowBorder_C">();
	}
	static class UBP_ShadowBorder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ShadowBorder_C>();
	}
};
static_assert(alignof(UBP_ShadowBorder_C) == 0x000008, "Wrong alignment on UBP_ShadowBorder_C");
static_assert(sizeof(UBP_ShadowBorder_C) == 0x000270, "Wrong size on UBP_ShadowBorder_C");

}

