#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpinnerBrick

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SpinnerBrick.BP_SpinnerBrick_C
// 0x0000 (0x0168 - 0x0168)
class UBP_SpinnerBrick_C final : public USpinnerBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SpinnerBrick_C">();
	}
	static class UBP_SpinnerBrick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SpinnerBrick_C>();
	}
};
static_assert(alignof(UBP_SpinnerBrick_C) == 0x000008, "Wrong alignment on UBP_SpinnerBrick_C");
static_assert(sizeof(UBP_SpinnerBrick_C) == 0x000168, "Wrong size on UBP_SpinnerBrick_C");

}

