#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sunrise_Sequence

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Sunrise_Sequence.BP_Sunrise_Sequence_C
// 0x0010 (0x0250 - 0x0240)
class ABP_Sunrise_Sequence_C final : public AMenuSequence
{
public:
	class UCameraComponent*                       Camera;                                            // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Sunrise_Sequence_C">();
	}
	static class ABP_Sunrise_Sequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Sunrise_Sequence_C>();
	}
};
static_assert(alignof(ABP_Sunrise_Sequence_C) == 0x000008, "Wrong alignment on ABP_Sunrise_Sequence_C");
static_assert(sizeof(ABP_Sunrise_Sequence_C) == 0x000250, "Wrong size on ABP_Sunrise_Sequence_C");
static_assert(offsetof(ABP_Sunrise_Sequence_C, Camera) == 0x000240, "Member 'ABP_Sunrise_Sequence_C::Camera' has a wrong offset!");
static_assert(offsetof(ABP_Sunrise_Sequence_C, DefaultSceneRoot) == 0x000248, "Member 'ABP_Sunrise_Sequence_C::DefaultSceneRoot' has a wrong offset!");

}

