#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Seat_5x2x1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Seat_5x2x1s.BP_Seat_5x2x1s_C
// 0x0000 (0x01B8 - 0x01B8)
class UBP_Seat_5x2x1s_C final : public USeatBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Seat_5x2x1s_C">();
	}
	static class UBP_Seat_5x2x1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Seat_5x2x1s_C>();
	}
};
static_assert(alignof(UBP_Seat_5x2x1s_C) == 0x000008, "Wrong alignment on UBP_Seat_5x2x1s_C");
static_assert(sizeof(UBP_Seat_5x2x1s_C) == 0x0001B8, "Wrong size on UBP_Seat_5x2x1s_C");

}

