#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Team_FireDepartment

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Team_FireDepartment.BP_Team_FireDepartment_C
// 0x0000 (0x00C8 - 0x00C8)
class UBP_Team_FireDepartment_C final : public UBrickTeam
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Team_FireDepartment_C">();
	}
	static class UBP_Team_FireDepartment_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Team_FireDepartment_C>();
	}
};
static_assert(alignof(UBP_Team_FireDepartment_C) == 0x000008, "Wrong alignment on UBP_Team_FireDepartment_C");
static_assert(sizeof(UBP_Team_FireDepartment_C) == 0x0000C8, "Wrong size on UBP_Team_FireDepartment_C");

}

