#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeamBase

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TeamBase.BP_TeamBase_C
// 0x0000 (0x0268 - 0x0268)
class ABP_TeamBase_C final : public ATeamBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TeamBase_C">();
	}
	static class ABP_TeamBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TeamBase_C>();
	}
};
static_assert(alignof(ABP_TeamBase_C) == 0x000008, "Wrong alignment on ABP_TeamBase_C");
static_assert(sizeof(ABP_TeamBase_C) == 0x000268, "Wrong size on ABP_TeamBase_C");

}

