#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wing_4x10x1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Wing_4x10x1s.BP_Wing_4x10x1s_C
// 0x0000 (0x0168 - 0x0168)
class UBP_Wing_4x10x1s_C final : public UWingBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Wing_4x10x1s_C">();
	}
	static class UBP_Wing_4x10x1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Wing_4x10x1s_C>();
	}
};
static_assert(alignof(UBP_Wing_4x10x1s_C) == 0x000008, "Wrong alignment on UBP_Wing_4x10x1s_C");
static_assert(sizeof(UBP_Wing_4x10x1s_C) == 0x000168, "Wrong size on UBP_Wing_4x10x1s_C");

}

