#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WidgetMacroLibrary

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WidgetMacroLibrary.BP_WidgetMacroLibrary_C
// 0x0000 (0x0108 - 0x0108)
class UBP_WidgetMacroLibrary_C final : public UWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WidgetMacroLibrary_C">();
	}
	static class UBP_WidgetMacroLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_WidgetMacroLibrary_C>();
	}
};
static_assert(alignof(UBP_WidgetMacroLibrary_C) == 0x000008, "Wrong alignment on UBP_WidgetMacroLibrary_C");
static_assert(sizeof(UBP_WidgetMacroLibrary_C) == 0x000108, "Wrong size on UBP_WidgetMacroLibrary_C");

}

