#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Army_Digital

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass C_Army_Digital.C_Army_Digital_C
// 0x0000 (0x0050 - 0x0050)
class UC_Army_Digital_C final : public UBrickPattern
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"C_Army_Digital_C">();
	}
	static class UC_Army_Digital_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UC_Army_Digital_C>();
	}
};
static_assert(alignof(UC_Army_Digital_C) == 0x000008, "Wrong alignment on UC_Army_Digital_C");
static_assert(sizeof(UC_Army_Digital_C) == 0x000050, "Wrong size on UC_Army_Digital_C");

}

