#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: City_North

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass City_North.City_North_C
// 0x0000 (0x0228 - 0x0228)
class ACity_North_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"City_North_C">();
	}
	static class ACity_North_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACity_North_C>();
	}
};
static_assert(alignof(ACity_North_C) == 0x000008, "Wrong alignment on ACity_North_C");
static_assert(sizeof(ACity_North_C) == 0x000228, "Wrong size on ACity_North_C");

}

