#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: City2

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass City2.City2_C
// 0x0000 (0x0228 - 0x0228)
class ACity2_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"City2_C">();
	}
	static class ACity2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACity2_C>();
	}
};
static_assert(alignof(ACity2_C) == 0x000008, "Wrong alignment on ACity2_C");
static_assert(sizeof(ACity2_C) == 0x000228, "Wrong size on ACity2_C");

}

