#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluUGC

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class FluUGC.FluUGCSubsystem
// 0x0030 (0x0060 - 0x0030)
class UFluUGCSubsystem : public UEngineSubsystem
{
public:
	uint8                                         Pad_30[0x30];                                      // 0x0030(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UFluUGCSubsystem* Get(const class FName& SubsystemName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FluUGCSubsystem">();
	}
	static class UFluUGCSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFluUGCSubsystem>();
	}
};
static_assert(alignof(UFluUGCSubsystem) == 0x000008, "Wrong alignment on UFluUGCSubsystem");
static_assert(sizeof(UFluUGCSubsystem) == 0x000060, "Wrong size on UFluUGCSubsystem");

}

