#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameLogoEnum

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum GameLogoEnum.GameLogoEnum
// NumValues: 0x0003
enum class EGameLogoEnum : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator2                           = 1,
	GameLogoEnum_MAX                         = 2,
};

}

