#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Suburb

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Suburb.Suburb_C
// 0x0000 (0x0228 - 0x0228)
class ASuburb_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Suburb_C">();
	}
	static class ASuburb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASuburb_C>();
	}
};
static_assert(alignof(ASuburb_C) == 0x000008, "Wrong alignment on ASuburb_C");
static_assert(sizeof(ASuburb_C) == 0x000228, "Wrong size on ASuburb_C");

}

