#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameLogo

#include "Basic.hpp"

#include "WBP_GameLogo_classes.hpp"
#include "WBP_GameLogo_parameters.hpp"


namespace SDK
{

// Function WBP_GameLogo.WBP_GameLogo_C.ExecuteUbergraph_WBP_GameLogo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameLogo_C::ExecuteUbergraph_WBP_GameLogo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "ExecuteUbergraph_WBP_GameLogo");

	Params::WBP_GameLogo_C_ExecuteUbergraph_WBP_GameLogo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameLogo.WBP_GameLogo_C.UpdateUIStyle
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UBrickUIStyle*              Style                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameLogo_C::UpdateUIStyle(const class UBrickUIStyle* Style)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "UpdateUIStyle");

	Params::WBP_GameLogo_C_UpdateUIStyle Parms{};

	Parms.Style = Style;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameLogo.WBP_GameLogo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameLogo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameLogo.WBP_GameLogo_C.UpdateLogo
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_GameLogo_C::UpdateLogo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "UpdateLogo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameLogo.WBP_GameLogo_C.SetLogo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EGameLogoEnum                           InLogo                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameLogo_C::SetLogo(EGameLogoEnum InLogo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "SetLogo");

	Params::WBP_GameLogo_C_SetLogo Parms{};

	Parms.InLogo = InLogo;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameLogo.WBP_GameLogo_C.InitMID
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UMaterialInstanceDynamic* UWBP_GameLogo_C::InitMID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "InitMID");

	Params::WBP_GameLogo_C_InitMID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_GameLogo.WBP_GameLogo_C.IsLogoReady
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWBP_GameLogo_C::IsLogoReady() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameLogo_C", "IsLogoReady");

	Params::WBP_GameLogo_C_IsLogoReady Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

