#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UGCMetaDataPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UGCMetaDataPopup.WBP_UGCMetaDataPopup_C
// 0x0008 (0x02A8 - 0x02A0)
class UWBP_UGCMetaDataPopup_C final : public UUGCMetaDataPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_UGCMetaDataPopup(int32 EntryPoint);
	void Construct();

	class FText GetPopupTitle() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UGCMetaDataPopup_C">();
	}
	static class UWBP_UGCMetaDataPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UGCMetaDataPopup_C>();
	}
};
static_assert(alignof(UWBP_UGCMetaDataPopup_C) == 0x000008, "Wrong alignment on UWBP_UGCMetaDataPopup_C");
static_assert(sizeof(UWBP_UGCMetaDataPopup_C) == 0x0002A8, "Wrong size on UWBP_UGCMetaDataPopup_C");
static_assert(offsetof(UWBP_UGCMetaDataPopup_C, UberGraphFrame) == 0x0002A0, "Member 'UWBP_UGCMetaDataPopup_C::UberGraphFrame' has a wrong offset!");

}

