#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUDIconContainer

#include "Basic.hpp"

#include "WBP_HUDIconContainer_classes.hpp"
#include "WBP_HUDIconContainer_parameters.hpp"


namespace SDK
{

// Function WBP_HUDIconContainer.WBP_HUDIconContainer_C.ExecuteUbergraph_WBP_HUDIconContainer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDIconContainer_C::ExecuteUbergraph_WBP_HUDIconContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDIconContainer_C", "ExecuteUbergraph_WBP_HUDIconContainer");

	Params::WBP_HUDIconContainer_C_ExecuteUbergraph_WBP_HUDIconContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDIconContainer.WBP_HUDIconContainer_C.AddCrosshairWidgets
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class UMapCrosshairWidget*>&Widgets                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UWBP_HUDIconContainer_C::AddCrosshairWidgets(const TArray<class UMapCrosshairWidget*>& Widgets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDIconContainer_C", "AddCrosshairWidgets");

	Params::WBP_HUDIconContainer_C_AddCrosshairWidgets Parms{};

	Parms.Widgets = std::move(Widgets);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDIconContainer.WBP_HUDIconContainer_C.AddInteractionWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UInteractionWidget*               Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDIconContainer_C::AddInteractionWidget(class UInteractionWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDIconContainer_C", "AddInteractionWidget");

	Params::WBP_HUDIconContainer_C_AddInteractionWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}

}

