#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PropertiesPanel

#include "Basic.hpp"

#include "WBP_PropertiesPanel_classes.hpp"
#include "WBP_PropertiesPanel_parameters.hpp"


namespace SDK
{

// Function WBP_PropertiesPanel.WBP_PropertiesPanel_C.AddCategoryWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UPropertyCategoryWidget*          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PropertiesPanel_C::AddCategoryWidget(class UPropertyCategoryWidget* Widget, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PropertiesPanel_C", "AddCategoryWidget");

	Params::WBP_PropertiesPanel_C_AddCategoryWidget Parms{};

	Parms.Widget = Widget;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PropertiesPanel.WBP_PropertiesPanel_C.ExecuteUbergraph_WBP_PropertiesPanel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PropertiesPanel_C::ExecuteUbergraph_WBP_PropertiesPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PropertiesPanel_C", "ExecuteUbergraph_WBP_PropertiesPanel");

	Params::WBP_PropertiesPanel_C_ExecuteUbergraph_WBP_PropertiesPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

