#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FlashSequenceItemWidget

#include "Basic.hpp"

#include "WBP_FlashSequenceItemWidget_classes.hpp"
#include "WBP_FlashSequenceItemWidget_parameters.hpp"


namespace SDK
{

// Function WBP_FlashSequenceItemWidget.WBP_FlashSequenceItemWidget_C.ExecuteUbergraph_WBP_FlashSequenceItemWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FlashSequenceItemWidget_C::ExecuteUbergraph_WBP_FlashSequenceItemWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FlashSequenceItemWidget_C", "ExecuteUbergraph_WBP_FlashSequenceItemWidget");

	Params::WBP_FlashSequenceItemWidget_C_ExecuteUbergraph_WBP_FlashSequenceItemWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FlashSequenceItemWidget.WBP_FlashSequenceItemWidget_C.UpdateIsLit
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewLit                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_FlashSequenceItemWidget_C::UpdateIsLit(bool bNewLit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FlashSequenceItemWidget_C", "UpdateIsLit");

	Params::WBP_FlashSequenceItemWidget_C_UpdateIsLit Parms{};

	Parms.bNewLit = bNewLit;

	UObject::ProcessEvent(Func, &Parms);
}

}

