#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ScoreboardPopup

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ScoreboardPopup.WBP_ScoreboardPopup_C
// 0x0010 (0x02A8 - 0x0298)
class UWBP_ScoreboardPopup_C final : public UScoreboardPopupWidget
{
public:
	class UWBP_MatchTimer_C*                      WBP_MatchTimer;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Scoreboard_C*                      WBP_Scoreboard;                                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ScoreboardPopup_C">();
	}
	static class UWBP_ScoreboardPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ScoreboardPopup_C>();
	}
};
static_assert(alignof(UWBP_ScoreboardPopup_C) == 0x000008, "Wrong alignment on UWBP_ScoreboardPopup_C");
static_assert(sizeof(UWBP_ScoreboardPopup_C) == 0x0002A8, "Wrong size on UWBP_ScoreboardPopup_C");
static_assert(offsetof(UWBP_ScoreboardPopup_C, WBP_MatchTimer) == 0x000298, "Member 'UWBP_ScoreboardPopup_C::WBP_MatchTimer' has a wrong offset!");
static_assert(offsetof(UWBP_ScoreboardPopup_C, WBP_Scoreboard) == 0x0002A0, "Member 'UWBP_ScoreboardPopup_C::WBP_Scoreboard' has a wrong offset!");

}

