#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DashboardIcon

#include "Basic.hpp"

#include "WBP_DashboardIcon_classes.hpp"
#include "WBP_DashboardIcon_parameters.hpp"


namespace SDK
{

// Function WBP_DashboardIcon.WBP_DashboardIcon_C.UpdateIconImage
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InIconIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DashboardIcon_C::UpdateIconImage(bool bInVisible, EBrickUIColorStyle InColorStyle, int32 InIconIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DashboardIcon_C", "UpdateIconImage");

	Params::WBP_DashboardIcon_C_UpdateIconImage Parms{};

	Parms.bInVisible = bInVisible;
	Parms.InColorStyle = InColorStyle;
	Parms.InIconIndex = InIconIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DashboardIcon.WBP_DashboardIcon_C.ExecuteUbergraph_WBP_DashboardIcon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DashboardIcon_C::ExecuteUbergraph_WBP_DashboardIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DashboardIcon_C", "ExecuteUbergraph_WBP_DashboardIcon");

	Params::WBP_DashboardIcon_C_ExecuteUbergraph_WBP_DashboardIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

