#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PingIndicator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PingIndicator.WBP_PingIndicator_C
// 0x0010 (0x0290 - 0x0280)
class UWBP_PingIndicator_C final : public UPingIndicatorWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0280(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBrickImage*                            ConnectionImage;                                   // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_PingIndicator(int32 EntryPoint);
	void UpdatePing(int32 InPing);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PingIndicator_C">();
	}
	static class UWBP_PingIndicator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PingIndicator_C>();
	}
};
static_assert(alignof(UWBP_PingIndicator_C) == 0x000008, "Wrong alignment on UWBP_PingIndicator_C");
static_assert(sizeof(UWBP_PingIndicator_C) == 0x000290, "Wrong size on UWBP_PingIndicator_C");
static_assert(offsetof(UWBP_PingIndicator_C, UberGraphFrame) == 0x000280, "Member 'UWBP_PingIndicator_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_PingIndicator_C, ConnectionImage) == 0x000288, "Member 'UWBP_PingIndicator_C::ConnectionImage' has a wrong offset!");

}

