#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputMappings

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_InputMappings.WBP_InputMappings_C
// 0x0010 (0x02A8 - 0x0298)
class UWBP_InputMappings_C final : public UInputSettingsPageWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FPopupHandle                           ResetPopupHandle;                                  // 0x02A0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void Construct();
	void OnClickedRevertInput();
	void OnRevertInputPopupClosed(EPopupResult Result);
	void ExecuteUbergraph_WBP_InputMappings(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_InputMappings_C">();
	}
	static class UWBP_InputMappings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InputMappings_C>();
	}
};
static_assert(alignof(UWBP_InputMappings_C) == 0x000008, "Wrong alignment on UWBP_InputMappings_C");
static_assert(sizeof(UWBP_InputMappings_C) == 0x0002A8, "Wrong size on UWBP_InputMappings_C");
static_assert(offsetof(UWBP_InputMappings_C, UberGraphFrame) == 0x000298, "Member 'UWBP_InputMappings_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_InputMappings_C, ResetPopupHandle) == 0x0002A0, "Member 'UWBP_InputMappings_C::ResetPopupHandle' has a wrong offset!");

}

