#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SocialMediaLink

#include "Basic.hpp"

#include "WBP_SocialMediaLink_classes.hpp"
#include "WBP_SocialMediaLink_parameters.hpp"


namespace SDK
{

// Function WBP_SocialMediaLink.WBP_SocialMediaLink_C.ExecuteUbergraph_WBP_SocialMediaLink
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SocialMediaLink_C::ExecuteUbergraph_WBP_SocialMediaLink(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SocialMediaLink_C", "ExecuteUbergraph_WBP_SocialMediaLink");

	Params::WBP_SocialMediaLink_C_ExecuteUbergraph_WBP_SocialMediaLink Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SocialMediaLink.WBP_SocialMediaLink_C.BndEvt__WBP_SocialMediaLink_WBP_BrickButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EBrickUIStyleState                      InContentStyleState                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SocialMediaLink_C::BndEvt__WBP_SocialMediaLink_WBP_BrickButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SocialMediaLink_C", "BndEvt__WBP_SocialMediaLink_WBP_BrickButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature");

	Params::WBP_SocialMediaLink_C_BndEvt__WBP_SocialMediaLink_WBP_BrickButton_K2Node_ComponentBoundEvent_1_OnUpdateContentStyle__DelegateSignature Parms{};

	Parms.InColorStyle = InColorStyle;
	Parms.InContentStyleState = InContentStyleState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SocialMediaLink.WBP_SocialMediaLink_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_SocialMediaLink_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SocialMediaLink_C", "PreConstruct");

	Params::WBP_SocialMediaLink_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SocialMediaLink.WBP_SocialMediaLink_C.BndEvt__WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_SocialMediaLink_C::BndEvt__WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SocialMediaLink_C", "BndEvt__WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

