#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickSlider

#include "Basic.hpp"

#include "WBP_BrickSlider_classes.hpp"
#include "WBP_BrickSlider_parameters.hpp"


namespace SDK
{

// Function WBP_BrickSlider.WBP_BrickSlider_C.ExecuteUbergraph_WBP_BrickSlider
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BrickSlider_C::ExecuteUbergraph_WBP_BrickSlider(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "ExecuteUbergraph_WBP_BrickSlider");

	Params::WBP_BrickSlider_C_ExecuteUbergraph_WBP_BrickSlider Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_BrickSlider_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.UpdateIsDragging
// (Event, Protected, BlueprintEvent)
// Parameters:
// const bool                              bIsDragging                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_BrickSlider_C::UpdateIsDragging(const bool bIsDragging)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "UpdateIsDragging");

	Params::WBP_BrickSlider_C_UpdateIsDragging Parms{};

	Parms.bIsDragging = bIsDragging;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_BrickSlider_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "PreConstruct");

	Params::WBP_BrickSlider_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.UpdateSliderPosition
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BrickSlider_C::UpdateSliderPosition(float NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "UpdateSliderPosition");

	Params::WBP_BrickSlider_C_UpdateSliderPosition Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.CreateModifierHintWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UInputKeyWidget*&                 Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FKey&                      Key                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// const struct FVector2D&                 Pivot                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EHorizontalAlignment                    HorizontalAlignment                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVerticalAlignment                      VerticalAlignment                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BrickSlider_C::CreateModifierHintWidget(class UInputKeyWidget*& Widget, const struct FKey& Key, const struct FVector2D& Pivot, EHorizontalAlignment HorizontalAlignment, EVerticalAlignment VerticalAlignment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "CreateModifierHintWidget");

	Params::WBP_BrickSlider_C_CreateModifierHintWidget Parms{};

	Parms.Widget = Widget;
	Parms.Key = std::move(Key);
	Parms.Pivot = std::move(Pivot);
	Parms.HorizontalAlignment = HorizontalAlignment;
	Parms.VerticalAlignment = VerticalAlignment;

	UObject::ProcessEvent(Func, &Parms);

	Widget = Parms.Widget;
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.PoolModifierHintWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UInputKeyWidget*&                 Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, InstancedReference, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BrickSlider_C::PoolModifierHintWidget(class UInputKeyWidget*& Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "PoolModifierHintWidget");

	Params::WBP_BrickSlider_C_PoolModifierHintWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);

	Widget = Parms.Widget;
}


// Function WBP_BrickSlider.WBP_BrickSlider_C.PoolAllModifierHintWidgets
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_BrickSlider_C::PoolAllModifierHintWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BrickSlider_C", "PoolAllModifierHintWidgets");

	UObject::ProcessEvent(Func, nullptr);
}

}

