#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SpawnScreen

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SpawnScreen.WBP_SpawnScreen_C
// 0x0000 (0x0278 - 0x0278)
class UWBP_SpawnScreen_C final : public USpawnScreenWidget
{
public:
	bool AddGameOverlayWidget(class UGameOverlayWidget* Widget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SpawnScreen_C">();
	}
	static class UWBP_SpawnScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SpawnScreen_C>();
	}
};
static_assert(alignof(UWBP_SpawnScreen_C) == 0x000008, "Wrong alignment on UWBP_SpawnScreen_C");
static_assert(sizeof(UWBP_SpawnScreen_C) == 0x000278, "Wrong size on UWBP_SpawnScreen_C");

}

