#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MenuButton.WBP_MenuButton_C
// 0x0008 (0x02A0 - 0x0298)
class UWBP_MenuButton_C final : public UMenuButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_MenuButton(int32 EntryPoint);
	void BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MenuButton_C">();
	}
	static class UWBP_MenuButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuButton_C>();
	}
};
static_assert(alignof(UWBP_MenuButton_C) == 0x000008, "Wrong alignment on UWBP_MenuButton_C");
static_assert(sizeof(UWBP_MenuButton_C) == 0x0002A0, "Wrong size on UWBP_MenuButton_C");
static_assert(offsetof(UWBP_MenuButton_C, UberGraphFrame) == 0x000298, "Member 'UWBP_MenuButton_C::UberGraphFrame' has a wrong offset!");

}

