#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReuploadPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ReuploadPopup.WBP_ReuploadPopup_C
// 0x0008 (0x02D0 - 0x02C8)
class UWBP_ReuploadPopup_C final : public UReuploadPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_ReuploadPopup(int32 EntryPoint);
	void Construct();

	class FText GetPopupTitle() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ReuploadPopup_C">();
	}
	static class UWBP_ReuploadPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ReuploadPopup_C>();
	}
};
static_assert(alignof(UWBP_ReuploadPopup_C) == 0x000008, "Wrong alignment on UWBP_ReuploadPopup_C");
static_assert(sizeof(UWBP_ReuploadPopup_C) == 0x0002D0, "Wrong size on UWBP_ReuploadPopup_C");
static_assert(offsetof(UWBP_ReuploadPopup_C, UberGraphFrame) == 0x0002C8, "Member 'UWBP_ReuploadPopup_C::UberGraphFrame' has a wrong offset!");

}

