#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_RandomSpawnIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_RandomSpawnIcon.WBP_RandomSpawnIcon_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_RandomSpawnIcon_C final : public UHUDIconWidget
{
public:
	class FText GetIconDisplayName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_RandomSpawnIcon_C">();
	}
	static class UWBP_RandomSpawnIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_RandomSpawnIcon_C>();
	}
};
static_assert(alignof(UWBP_RandomSpawnIcon_C) == 0x000008, "Wrong alignment on UWBP_RandomSpawnIcon_C");
static_assert(sizeof(UWBP_RandomSpawnIcon_C) == 0x000288, "Wrong size on UWBP_RandomSpawnIcon_C");

}

