#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PagedListEntry

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PagedListEntry.WBP_PagedListEntry_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_PagedListEntry_C final : public UPagedListEntryWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PagedListEntry_C">();
	}
	static class UWBP_PagedListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PagedListEntry_C>();
	}
};
static_assert(alignof(UWBP_PagedListEntry_C) == 0x000008, "Wrong alignment on UWBP_PagedListEntry_C");
static_assert(sizeof(UWBP_PagedListEntry_C) == 0x000288, "Wrong size on UWBP_PagedListEntry_C");

}

