#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReuploadPopup

#include "Basic.hpp"

#include "WBP_ReuploadPopup_classes.hpp"
#include "WBP_ReuploadPopup_parameters.hpp"


namespace SDK
{

// Function WBP_ReuploadPopup.WBP_ReuploadPopup_C.ExecuteUbergraph_WBP_ReuploadPopup
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReuploadPopup_C::ExecuteUbergraph_WBP_ReuploadPopup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReuploadPopup_C", "ExecuteUbergraph_WBP_ReuploadPopup");

	Params::WBP_ReuploadPopup_C_ExecuteUbergraph_WBP_ReuploadPopup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReuploadPopup.WBP_ReuploadPopup_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ReuploadPopup_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReuploadPopup_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReuploadPopup.WBP_ReuploadPopup_C.GetPopupTitle
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UWBP_ReuploadPopup_C::GetPopupTitle() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReuploadPopup_C", "GetPopupTitle");

	Params::WBP_ReuploadPopup_C_GetPopupTitle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

