#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CursorIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CursorIcon.WBP_CursorIcon_C
// 0x0000 (0x0288 - 0x0288)
class UWBP_CursorIcon_C final : public UHUDIconWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CursorIcon_C">();
	}
	static class UWBP_CursorIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CursorIcon_C>();
	}
};
static_assert(alignof(UWBP_CursorIcon_C) == 0x000008, "Wrong alignment on UWBP_CursorIcon_C");
static_assert(sizeof(UWBP_CursorIcon_C) == 0x000288, "Wrong size on UWBP_CursorIcon_C");

}

