#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CapturePointIcon

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CapturePointIcon.WBP_CapturePointIcon_C
// 0x0000 (0x02C8 - 0x02C8)
class UWBP_CapturePointIcon_C final : public UCapturePointIconWidget
{
public:
	class FText GetIconDisplayName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_CapturePointIcon_C">();
	}
	static class UWBP_CapturePointIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CapturePointIcon_C>();
	}
};
static_assert(alignof(UWBP_CapturePointIcon_C) == 0x000008, "Wrong alignment on UWBP_CapturePointIcon_C");
static_assert(sizeof(UWBP_CapturePointIcon_C) == 0x0002C8, "Wrong size on UWBP_CapturePointIcon_C");

}

