#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UnsavedChangesPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_UnsavedChangesPopup.WBP_UnsavedChangesPopup_C
// 0x0008 (0x02A0 - 0x0298)
class UWBP_UnsavedChangesPopup_C final : public UUnsavedChangesPopupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Construct();
	void DiscardChanges();
	void SaveChanges();
	void ExecuteUbergraph_WBP_UnsavedChangesPopup(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_UnsavedChangesPopup_C">();
	}
	static class UWBP_UnsavedChangesPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UnsavedChangesPopup_C>();
	}
};
static_assert(alignof(UWBP_UnsavedChangesPopup_C) == 0x000008, "Wrong alignment on UWBP_UnsavedChangesPopup_C");
static_assert(sizeof(UWBP_UnsavedChangesPopup_C) == 0x0002A0, "Wrong size on UWBP_UnsavedChangesPopup_C");
static_assert(offsetof(UWBP_UnsavedChangesPopup_C, UberGraphFrame) == 0x000298, "Member 'UWBP_UnsavedChangesPopup_C::UberGraphFrame' has a wrong offset!");

}

