#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InputActionCategory

#include "Basic.hpp"

#include "WBP_InputActionCategory_classes.hpp"
#include "WBP_InputActionCategory_parameters.hpp"


namespace SDK
{

// Function WBP_InputActionCategory.WBP_InputActionCategory_C.ExecuteUbergraph_WBP_InputActionCategory
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InputActionCategory_C::ExecuteUbergraph_WBP_InputActionCategory(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "ExecuteUbergraph_WBP_InputActionCategory");

	Params::WBP_InputActionCategory_C_ExecuteUbergraph_WBP_InputActionCategory Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.UpdateInputActionListMode
// (Event, Protected, BlueprintEvent)
// Parameters:
// EInputActionListMode                    NewMode                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InputActionCategory_C::UpdateInputActionListMode(EInputActionListMode NewMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "UpdateInputActionListMode");

	Params::WBP_InputActionCategory_C_UpdateInputActionListMode Parms{};

	Parms.NewMode = NewMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.UpdateIsSelected
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewSelected                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_InputActionCategory_C::UpdateIsSelected(bool bNewSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "UpdateIsSelected");

	Params::WBP_InputActionCategory_C_UpdateIsSelected Parms{};

	Parms.bNewSelected = bNewSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.InitializeCategory
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      InCategoryName                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_InputActionCategory_C::InitializeCategory(const class FText& InCategoryName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "InitializeCategory");

	Params::WBP_InputActionCategory_C_InitializeCategory Parms{};

	Parms.InCategoryName = std::move(InCategoryName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_InputActionCategory_C::BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "BndEvt__Button_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EBrickUIStyleState                      InContentStyleState                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InputActionCategory_C::BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature");

	Params::WBP_InputActionCategory_C_BndEvt__Button_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature Parms{};

	Parms.InColorStyle = InColorStyle;
	Parms.InContentStyleState = InContentStyleState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InputActionCategory.WBP_InputActionCategory_C.GetWidgetToFocus
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_InputActionCategory_C::GetWidgetToFocus() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InputActionCategory_C", "GetWidgetToFocus");

	Params::WBP_InputActionCategory_C_GetWidgetToFocus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

