#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUDContainer

#include "Basic.hpp"

#include "WBP_HUDContainer_classes.hpp"
#include "WBP_HUDContainer_parameters.hpp"


namespace SDK
{

// Function WBP_HUDContainer.WBP_HUDContainer_C.ExecuteUbergraph_WBP_HUDContainer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDContainer_C::ExecuteUbergraph_WBP_HUDContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDContainer_C", "ExecuteUbergraph_WBP_HUDContainer");

	Params::WBP_HUDContainer_C_ExecuteUbergraph_WBP_HUDContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDContainer.WBP_HUDContainer_C.AddHUDWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDContainer_C::AddHUDWidget(class UUserWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDContainer_C", "AddHUDWidget");

	Params::WBP_HUDContainer_C_AddHUDWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDContainer.WBP_HUDContainer_C.AddGameOverlayWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UGameOverlayWidget*               Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDContainer_C::AddGameOverlayWidget(class UGameOverlayWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDContainer_C", "AddGameOverlayWidget");

	Params::WBP_HUDContainer_C_AddGameOverlayWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}

}

