#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StructProperty

#include "Basic.hpp"

#include "WBP_StructProperty_classes.hpp"
#include "WBP_StructProperty_parameters.hpp"


namespace SDK
{

// Function WBP_StructProperty.WBP_StructProperty_C.ExecuteUbergraph_WBP_StructProperty
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StructProperty_C::ExecuteUbergraph_WBP_StructProperty(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StructProperty_C", "ExecuteUbergraph_WBP_StructProperty");

	Params::WBP_StructProperty_C_ExecuteUbergraph_WBP_StructProperty Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StructProperty.WBP_StructProperty_C.AddPropertyContainerWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class UPropertyContainerWidget*         Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StructProperty_C::AddPropertyContainerWidget(class UPropertyContainerWidget* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StructProperty_C", "AddPropertyContainerWidget");

	Params::WBP_StructProperty_C_AddPropertyContainerWidget Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_StructProperty.WBP_StructProperty_C.UpdatePropertyContainerWidgetSlot
// (Event, Public, BlueprintEvent)
// Parameters:
// class UPropertyContainerWidget*         Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NumPerRow                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_StructProperty_C::UpdatePropertyContainerWidgetSlot(class UPropertyContainerWidget* Widget, int32 Index_0, int32 NumPerRow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_StructProperty_C", "UpdatePropertyContainerWidgetSlot");

	Params::WBP_StructProperty_C_UpdatePropertyContainerWidgetSlot Parms{};

	Parms.Widget = Widget;
	Parms.Index_0 = Index_0;
	Parms.NumPerRow = NumPerRow;

	UObject::ProcessEvent(Func, &Parms);
}

}

