#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EnumProperty

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EnumProperty.WBP_EnumProperty_C
// 0x0000 (0x0298 - 0x0298)
class UWBP_EnumProperty_C final : public UEnumPropertyWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_EnumProperty_C">();
	}
	static class UWBP_EnumProperty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EnumProperty_C>();
	}
};
static_assert(alignof(UWBP_EnumProperty_C) == 0x000008, "Wrong alignment on UWBP_EnumProperty_C");
static_assert(sizeof(UWBP_EnumProperty_C) == 0x000298, "Wrong size on UWBP_EnumProperty_C");

}

