#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUDNotification

#include "Basic.hpp"

#include "WBP_HUDNotification_classes.hpp"
#include "WBP_HUDNotification_parameters.hpp"


namespace SDK
{

// Function WBP_HUDNotification.WBP_HUDNotification_C.ExecuteUbergraph_WBP_HUDNotification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDNotification_C::ExecuteUbergraph_WBP_HUDNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "ExecuteUbergraph_WBP_HUDNotification");

	Params::WBP_HUDNotification_C_ExecuteUbergraph_WBP_HUDNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.InitializeNotification
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBrickUIIconSlot&          InIconSlot                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// const class FText&                      InText                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUDNotification_C::InitializeNotification(const struct FBrickUIIconSlot& InIconSlot, const class FText& InText, EBrickUIColorStyle InColorStyle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "InitializeNotification");

	Params::WBP_HUDNotification_C_InitializeNotification Parms{};

	Parms.InIconSlot = std::move(InIconSlot);
	Parms.InText = std::move(InText);
	Parms.InColorStyle = InColorStyle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.UpdateIsThumbnailNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewIsThumbnail                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_HUDNotification_C::UpdateIsThumbnailNotification(bool bNewIsThumbnail)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "UpdateIsThumbnailNotification");

	Params::WBP_HUDNotification_C_UpdateIsThumbnailNotification Parms{};

	Parms.bNewIsThumbnail = bNewIsThumbnail;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.PlayFadeOutAnim
// (Event, Protected, BlueprintEvent)

void UWBP_HUDNotification_C::PlayFadeOutAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "PlayFadeOutAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUDNotification.WBP_HUDNotification_C.PlayFadeInAnim
// (Event, Protected, BlueprintEvent)

void UWBP_HUDNotification_C::PlayFadeInAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUDNotification_C", "PlayFadeInAnim");

	UObject::ProcessEvent(Func, nullptr);
}

}

