#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Credits

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Credits.WBP_Credits_C
// 0x0008 (0x0278 - 0x0270)
class UWBP_Credits_C final : public UMenuPageWidget
{
public:
	class UWBP_SocialMediaLink_C*                 WBP_CreditsLink_74;                                // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Credits_C">();
	}
	static class UWBP_Credits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Credits_C>();
	}
};
static_assert(alignof(UWBP_Credits_C) == 0x000008, "Wrong alignment on UWBP_Credits_C");
static_assert(sizeof(UWBP_Credits_C) == 0x000278, "Wrong size on UWBP_Credits_C");
static_assert(offsetof(UWBP_Credits_C, WBP_CreditsLink_74) == 0x000270, "Member 'UWBP_Credits_C::WBP_CreditsLink_74' has a wrong offset!");

}

