#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ConnectorSpacingAxis

#include "Basic.hpp"

#include "WBP_ConnectorSpacingAxis_classes.hpp"
#include "WBP_ConnectorSpacingAxis_parameters.hpp"


namespace SDK
{

// Function WBP_ConnectorSpacingAxis.WBP_ConnectorSpacingAxis_C.ExecuteUbergraph_WBP_ConnectorSpacingAxis
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ConnectorSpacingAxis_C::ExecuteUbergraph_WBP_ConnectorSpacingAxis(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConnectorSpacingAxis_C", "ExecuteUbergraph_WBP_ConnectorSpacingAxis");

	Params::WBP_ConnectorSpacingAxis_C_ExecuteUbergraph_WBP_ConnectorSpacingAxis Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ConnectorSpacingAxis.WBP_ConnectorSpacingAxis_C.UpdateSpacingAxis
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EFluAxisSigned                          InSpacingAxis                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EConnectorSpacing                       InSpacing                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ConnectorSpacingAxis_C::UpdateSpacingAxis(EFluAxisSigned InSpacingAxis, EConnectorSpacing InSpacing)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConnectorSpacingAxis_C", "UpdateSpacingAxis");

	Params::WBP_ConnectorSpacingAxis_C_UpdateSpacingAxis Parms{};

	Parms.InSpacingAxis = InSpacingAxis;
	Parms.InSpacing = InSpacing;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ConnectorSpacingAxis.WBP_ConnectorSpacingAxis_C.BndEvt__WBP_ConnectorSpacingAxis_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_ConnectorSpacingAxis_C::BndEvt__WBP_ConnectorSpacingAxis_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConnectorSpacingAxis_C", "BndEvt__WBP_ConnectorSpacingAxis_Button_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ConnectorSpacingAxis.WBP_ConnectorSpacingAxis_C.BndEvt__WBP_ConnectorSpacingAxis_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature
// (BlueprintEvent)
// Parameters:
// EBrickUIColorStyle                      InColorStyle                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EBrickUIStyleState                      InContentStyleState                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ConnectorSpacingAxis_C::BndEvt__WBP_ConnectorSpacingAxis_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature(EBrickUIColorStyle InColorStyle, EBrickUIStyleState InContentStyleState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ConnectorSpacingAxis_C", "BndEvt__WBP_ConnectorSpacingAxis_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature");

	Params::WBP_ConnectorSpacingAxis_C_BndEvt__WBP_ConnectorSpacingAxis_WBP_BrickButton_K2Node_ComponentBoundEvent_0_OnUpdateContentStyle__DelegateSignature Parms{};

	Parms.InColorStyle = InColorStyle;
	Parms.InContentStyleState = InContentStyleState;

	UObject::ProcessEvent(Func, &Parms);
}

}

