#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdminMenu

#include "Basic.hpp"

#include "WBP_AdminMenu_classes.hpp"
#include "WBP_AdminMenu_parameters.hpp"


namespace SDK
{

// Function WBP_AdminMenu.WBP_AdminMenu_C.ExecuteUbergraph_WBP_AdminMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AdminMenu_C::ExecuteUbergraph_WBP_AdminMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdminMenu_C", "ExecuteUbergraph_WBP_AdminMenu");

	Params::WBP_AdminMenu_C_ExecuteUbergraph_WBP_AdminMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AdminMenu.WBP_AdminMenu_C.UpdateCanViewAndEditKicks
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewCanViewAndEdit                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_AdminMenu_C::UpdateCanViewAndEditKicks(bool bNewCanViewAndEdit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdminMenu_C", "UpdateCanViewAndEditKicks");

	Params::WBP_AdminMenu_C_UpdateCanViewAndEditKicks Parms{};

	Parms.bNewCanViewAndEdit = bNewCanViewAndEdit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AdminMenu.WBP_AdminMenu_C.UpdateHasSelectedKick
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bNewSelected                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_AdminMenu_C::UpdateHasSelectedKick(bool bNewSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdminMenu_C", "UpdateHasSelectedKick");

	Params::WBP_AdminMenu_C_UpdateHasSelectedKick Parms{};

	Parms.bNewSelected = bNewSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AdminMenu.WBP_AdminMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_AdminMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AdminMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

