#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WindowManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_WindowManager.WBP_WindowManager_C
// 0x0008 (0x03C8 - 0x03C0)
class UWBP_WindowManager_C final : public UWindowManagerWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_WindowManager(int32 EntryPoint);
	void AddActiveWidget(class UMainWidgetBase* Widget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_WindowManager_C">();
	}
	static class UWBP_WindowManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WindowManager_C>();
	}
};
static_assert(alignof(UWBP_WindowManager_C) == 0x000008, "Wrong alignment on UWBP_WindowManager_C");
static_assert(sizeof(UWBP_WindowManager_C) == 0x0003C8, "Wrong size on UWBP_WindowManager_C");
static_assert(offsetof(UWBP_WindowManager_C, UberGraphFrame) == 0x0003C0, "Member 'UWBP_WindowManager_C::UberGraphFrame' has a wrong offset!");

}

